# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/gps/GPS_Ver/Acq_Track_AC701/Acq_Track_AC701.srcs/sources_1/ip/blk_mem_I1/blk_mem_I1.xci
# IP: The module: 'blk_mem_I1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/gps/GPS_Ver/Acq_Track_AC701/Acq_Track_AC701.srcs/sources_1/ip/blk_mem_I1/blk_mem_I1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_I1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/gps/GPS_Ver/Acq_Track_AC701/Acq_Track_AC701.srcs/sources_1/ip/blk_mem_I1/blk_mem_I1.xci
# IP: The module: 'blk_mem_I1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/gps/GPS_Ver/Acq_Track_AC701/Acq_Track_AC701.srcs/sources_1/ip/blk_mem_I1/blk_mem_I1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_I1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
