set_property SRC_FILE_INFO {cfile:/home/zaid/MTP/myrepo/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.runs/synth_1/.Xil/Vivado-8653-zaid-LIFEBOOK-A555/dcp/clk_wiz_0_in_context.xdc rfile:../dcp/clk_wiz_0_in_context.xdc id:1 order:EARLY scoped_inst:CLOCK_NETWORK} [current_design]
set_property SRC_FILE_INFO {cfile:/home/zaid/MTP/myrepo/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.runs/synth_1/.Xil/Vivado-8653-zaid-LIFEBOOK-A555/dcp_2/blk_mem_I_in_context.xdc rfile:../dcp_2/blk_mem_I_in_context.xdc id:2 order:EARLY scoped_inst:MEM/MEM_I1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/zaid/MTP/myrepo/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.runs/synth_1/.Xil/Vivado-8653-zaid-LIFEBOOK-A555/dcp_2/blk_mem_I_in_context.xdc rfile:../dcp_2/blk_mem_I_in_context.xdc id:3 order:EARLY scoped_inst:MEM/MEM_I2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/zaid/MTP/myrepo/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.runs/synth_1/.Xil/Vivado-8653-zaid-LIFEBOOK-A555/dcp_3/blk_mem_I1_in_context.xdc rfile:../dcp_3/blk_mem_I1_in_context.xdc id:4 order:EARLY scoped_inst:MEM/MEM_I3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/zaid/MTP/myrepo/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.runs/synth_1/.Xil/Vivado-8653-zaid-LIFEBOOK-A555/dcp_4/blk_mem_Q_in_context.xdc rfile:../dcp_4/blk_mem_Q_in_context.xdc id:5 order:EARLY scoped_inst:MEM/MEM_Q1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/zaid/MTP/myrepo/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.runs/synth_1/.Xil/Vivado-8653-zaid-LIFEBOOK-A555/dcp_4/blk_mem_Q_in_context.xdc rfile:../dcp_4/blk_mem_Q_in_context.xdc id:6 order:EARLY scoped_inst:MEM/MEM_Q2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/zaid/MTP/myrepo/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.runs/synth_1/.Xil/Vivado-8653-zaid-LIFEBOOK-A555/dcp_5/blk_mem_Q1_in_context.xdc rfile:../dcp_5/blk_mem_Q1_in_context.xdc id:7 order:EARLY scoped_inst:MEM/MEM_Q3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/zaid/MTP/myrepo/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.runs/synth_1/.Xil/Vivado-8653-zaid-LIFEBOOK-A555/dcp_6/ila_0_in_context.xdc rfile:../dcp_6/ila_0_in_context.xdc id:8 order:EARLY scoped_inst:Acq_MOD/ILA_Acq2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/zaid/MTP/myrepo/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.runs/synth_1/.Xil/Vivado-8653-zaid-LIFEBOOK-A555/dcp_7/ila_1_in_context.xdc rfile:../dcp_7/ila_1_in_context.xdc id:9 order:EARLY scoped_inst:Acq_MOD/ILA_Acq1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/zaid/MTP/myrepo/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.runs/synth_1/.Xil/Vivado-8653-zaid-LIFEBOOK-A555/dcp_8/ila_2_in_context.xdc rfile:../dcp_8/ila_2_in_context.xdc id:10 order:EARLY scoped_inst:Acq_MOD/ILA_Acq3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/zaid/MTP/myrepo/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.runs/synth_1/.Xil/Vivado-8653-zaid-LIFEBOOK-A555/dcp_9/ila_3_in_context.xdc rfile:../dcp_9/ila_3_in_context.xdc id:11 order:EARLY scoped_inst:Acq_MOD/pk_metric_sorter/ila_sort} [current_design]
set_property SRC_FILE_INFO {cfile:/home/zaid/MTP/myrepo/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.srcs/constrs_1/imports/new/constr.xdc rfile:../../../../../Acq_Track_VCU108.srcs/constrs_1/imports/new/constr.xdc id:12} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports sys_clk_n]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports sys_clk_n]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports sys_clk_p]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports sys_clk_p]
set_property src_info {type:SCOPED_XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells CLOCK_NETWORK]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins MEM/MEM_I1/clka]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins MEM/MEM_I1/clkb]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells MEM/MEM_I1]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins MEM/MEM_I2/clka]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins MEM/MEM_I2/clkb]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells MEM/MEM_I2]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins MEM/MEM_I3/clka]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells MEM/MEM_I3]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins MEM/MEM_Q1/clka]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins MEM/MEM_Q1/clkb]
set_property src_info {type:SCOPED_XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells MEM/MEM_Q1]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins MEM/MEM_Q2/clka]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins MEM/MEM_Q2/clkb]
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells MEM/MEM_Q2]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins MEM/MEM_Q3/clka]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells MEM/MEM_Q3]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins Acq_MOD/ILA_Acq2/clk]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells Acq_MOD/ILA_Acq2]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins Acq_MOD/ILA_Acq1/clk]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells Acq_MOD/ILA_Acq1]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins Acq_MOD/ILA_Acq3/clk]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells Acq_MOD/ILA_Acq3]
set_property src_info {type:SCOPED_XDC file:11 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins Acq_MOD/pk_metric_sorter/ila_sort/clk]
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells Acq_MOD/pk_metric_sorter/ila_sort]
set_property src_info {type:XDC file:12 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [get_ports sys_clk_p]
set_property src_info {type:XDC file:12 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [get_ports sys_clk_n]
set_property src_info {type:XDC file:12 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS12 [get_ports reset]
set_property src_info {type:XDC file:12 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS12 [get_ports FinalOut]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 -name sys_clk_p [get_ports sys_clk_p]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports sys_clk_p] -edges {1 2 3} -edge_shift {0.000 2.667 5.333} [get_pins CLOCK_NETWORK/clk_out1]
