# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/sum_1_clock.xdc

# XDC: imports/common/jtag_hwcosim_top.xdc

# Block Designs: bd/hwcosim_top/hwcosim_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwcosim_top || ORIG_REF_NAME==hwcosim_top}]

# IP: bd/hwcosim_top/ip/hwcosim_top_sys_clk_wiz_0/hwcosim_top_sys_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwcosim_top_sys_clk_wiz_0 || ORIG_REF_NAME==hwcosim_top_sys_clk_wiz_0}]

# IP: bd/hwcosim_top/ip/hwcosim_top_hwc_jtag_axi_transport_0_0/hwcosim_top_hwc_jtag_axi_transport_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwcosim_top_hwc_jtag_axi_transport_0_0 || ORIG_REF_NAME==hwcosim_top_hwc_jtag_axi_transport_0_0}]

# IP: bd/hwcosim_top/ip/hwcosim_top_axis_data_fifo_rx_0/hwcosim_top_axis_data_fifo_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwcosim_top_axis_data_fifo_rx_0 || ORIG_REF_NAME==hwcosim_top_axis_data_fifo_rx_0}]

# IP: bd/hwcosim_top/ip/hwcosim_top_axis_data_fifo_tx_0/hwcosim_top_axis_data_fifo_tx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwcosim_top_axis_data_fifo_tx_0 || ORIG_REF_NAME==hwcosim_top_axis_data_fifo_tx_0}]

# IP: bd/hwcosim_top/ip/hwcosim_top_axis_dwidth_converter_rx_0/hwcosim_top_axis_dwidth_converter_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwcosim_top_axis_dwidth_converter_rx_0 || ORIG_REF_NAME==hwcosim_top_axis_dwidth_converter_rx_0}]

# IP: bd/hwcosim_top/ip/hwcosim_top_hwcosim_cmd_proc_0/hwcosim_top_hwcosim_cmd_proc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwcosim_top_hwcosim_cmd_proc_0 || ORIG_REF_NAME==hwcosim_top_hwcosim_cmd_proc_0}]

# IP: bd/hwcosim_top/ip/hwcosim_top_axis_dwidth_converter_tx_0/hwcosim_top_axis_dwidth_converter_tx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwcosim_top_axis_dwidth_converter_tx_0 || ORIG_REF_NAME==hwcosim_top_axis_dwidth_converter_tx_0}]

# IP: bd/hwcosim_top/ip/hwcosim_top_proc_sys_reset_0/hwcosim_top_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwcosim_top_proc_sys_reset_0 || ORIG_REF_NAME==hwcosim_top_proc_sys_reset_0}]

# IP: bd/hwcosim_top/ip/hwcosim_top_xlconstant_0_0/hwcosim_top_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwcosim_top_xlconstant_0_0 || ORIG_REF_NAME==hwcosim_top_xlconstant_0_0}]

# IP: bd/hwcosim_top/ip/hwcosim_top_sum_1_0_0/hwcosim_top_sum_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hwcosim_top_sum_1_0_0 || ORIG_REF_NAME==hwcosim_top_sum_1_0_0}]

# IP: bd/hwcosim_top/ip/hwcosim_top_sum_1_0_0/sum_1_blk_mem_gen_v8_3_i0/sum_1_blk_mem_gen_v8_3_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_1_blk_mem_gen_v8_3_i0 || ORIG_REF_NAME==sum_1_blk_mem_gen_v8_3_i0}]

# IP: bd/hwcosim_top/ip/hwcosim_top_sum_1_0_0/sum_1_c_counter_binary_v12_0_i0/sum_1_c_counter_binary_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_1_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==sum_1_c_counter_binary_v12_0_i0}]

# XDC: bd/hwcosim_top/ip/hwcosim_top_sys_clk_wiz_0/hwcosim_top_sys_clk_wiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hwcosim_top_sys_clk_wiz_0 || ORIG_REF_NAME==hwcosim_top_sys_clk_wiz_0}] {/inst }]/inst ]]

# XDC: bd/hwcosim_top/ip/hwcosim_top_sys_clk_wiz_0/hwcosim_top_sys_clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hwcosim_top_sys_clk_wiz_0 || ORIG_REF_NAME==hwcosim_top_sys_clk_wiz_0}] {/inst }]/inst ]]

# XDC: bd/hwcosim_top/ip/hwcosim_top_sys_clk_wiz_0/hwcosim_top_sys_clk_wiz_0_ooc.xdc

# XDC: bd/hwcosim_top/ip/hwcosim_top_axis_data_fifo_rx_0/hwcosim_top_axis_data_fifo_rx_0_ooc.xdc

# XDC: bd/hwcosim_top/ip/hwcosim_top_axis_data_fifo_rx_0/hwcosim_top_axis_data_fifo_rx_0/hwcosim_top_axis_data_fifo_rx_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hwcosim_top_axis_data_fifo_rx_0 || ORIG_REF_NAME==hwcosim_top_axis_data_fifo_rx_0}] {/inst }]/inst ]]

# XDC: bd/hwcosim_top/ip/hwcosim_top_axis_data_fifo_rx_0/hwcosim_top_axis_data_fifo_rx_0/hwcosim_top_axis_data_fifo_rx_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hwcosim_top_axis_data_fifo_rx_0 || ORIG_REF_NAME==hwcosim_top_axis_data_fifo_rx_0}] {/inst }]/inst ]]

# XDC: bd/hwcosim_top/ip/hwcosim_top_axis_data_fifo_tx_0/hwcosim_top_axis_data_fifo_tx_0_ooc.xdc

# XDC: bd/hwcosim_top/ip/hwcosim_top_axis_data_fifo_tx_0/hwcosim_top_axis_data_fifo_tx_0/hwcosim_top_axis_data_fifo_tx_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hwcosim_top_axis_data_fifo_tx_0 || ORIG_REF_NAME==hwcosim_top_axis_data_fifo_tx_0}] {/inst }]/inst ]]

# XDC: bd/hwcosim_top/ip/hwcosim_top_axis_data_fifo_tx_0/hwcosim_top_axis_data_fifo_tx_0/hwcosim_top_axis_data_fifo_tx_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hwcosim_top_axis_data_fifo_tx_0 || ORIG_REF_NAME==hwcosim_top_axis_data_fifo_tx_0}] {/inst }]/inst ]]

# XDC: bd/hwcosim_top/ip/hwcosim_top_axis_dwidth_converter_rx_0/hwcosim_top_axis_dwidth_converter_rx_0_ooc.xdc

# XDC: bd/hwcosim_top/ip/hwcosim_top_axis_dwidth_converter_tx_0/hwcosim_top_axis_dwidth_converter_tx_0_ooc.xdc

# XDC: bd/hwcosim_top/ip/hwcosim_top_proc_sys_reset_0/hwcosim_top_proc_sys_reset_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hwcosim_top_proc_sys_reset_0 || ORIG_REF_NAME==hwcosim_top_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/hwcosim_top/ip/hwcosim_top_proc_sys_reset_0/hwcosim_top_proc_sys_reset_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hwcosim_top_proc_sys_reset_0 || ORIG_REF_NAME==hwcosim_top_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/hwcosim_top/ip/hwcosim_top_proc_sys_reset_0/hwcosim_top_proc_sys_reset_0_ooc.xdc

# XDC: bd/hwcosim_top/ip/hwcosim_top_sum_1_0_0/sum_1_blk_mem_gen_v8_3_i0/sum_1_blk_mem_gen_v8_3_i0_ooc.xdc

# XDC: bd/hwcosim_top/ip/hwcosim_top_sum_1_0_0/sum_1_c_counter_binary_v12_0_i0/sum_1_c_counter_binary_v12_0_i0_ooc.xdc

# XDC: bd/hwcosim_top/ip/hwcosim_top_sum_1_0_0/constrs/sum_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hwcosim_top_sum_1_0_0 || ORIG_REF_NAME==hwcosim_top_sum_1_0_0}] {/inst }]/inst ]]

# XDC: bd/hwcosim_top/hwcosim_top_ooc.xdc
