# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.cache/wt [current_project]
set_property parent.project_path /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:0.9 [current_project]
set_property ip_repo_paths {
  /home/zaid/MTP/myrepo/sysgen/netlist/ip
  /home/zaid/Vivado/2016.1/data/sysgen/hwcosim_ip_repos
} [current_project]
add_files /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_sum_1_0_0/sum_1_blk_mem_gen_v8_3_i0_vivado.coe
add_files /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/hwcosim_top.bd
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_sys_clk_wiz_0/hwcosim_top_sys_clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_sys_clk_wiz_0/hwcosim_top_sys_clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_sys_clk_wiz_0/hwcosim_top_sys_clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_axis_data_fifo_rx_0/hwcosim_top_axis_data_fifo_rx_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_axis_data_fifo_rx_0/hwcosim_top_axis_data_fifo_rx_0/hwcosim_top_axis_data_fifo_rx_0.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_axis_data_fifo_rx_0/hwcosim_top_axis_data_fifo_rx_0/hwcosim_top_axis_data_fifo_rx_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_axis_data_fifo_tx_0/hwcosim_top_axis_data_fifo_tx_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_axis_data_fifo_tx_0/hwcosim_top_axis_data_fifo_tx_0/hwcosim_top_axis_data_fifo_tx_0.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_axis_data_fifo_tx_0/hwcosim_top_axis_data_fifo_tx_0/hwcosim_top_axis_data_fifo_tx_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_axis_dwidth_converter_rx_0/hwcosim_top_axis_dwidth_converter_rx_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_axis_dwidth_converter_tx_0/hwcosim_top_axis_dwidth_converter_tx_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_proc_sys_reset_0/hwcosim_top_proc_sys_reset_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_proc_sys_reset_0/hwcosim_top_proc_sys_reset_0.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_proc_sys_reset_0/hwcosim_top_proc_sys_reset_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_sum_1_0_0/sum_1_blk_mem_gen_v8_3_i0/sum_1_blk_mem_gen_v8_3_i0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_sum_1_0_0/sum_1_c_counter_binary_v12_0_i0/sum_1_c_counter_binary_v12_0_i0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/ip/hwcosim_top_sum_1_0_0/constrs/sum_1.xdc]
set_property used_in_implementation false [get_files -all /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/hwcosim_top_ooc.xdc]
set_property is_locked true [get_files /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/hwcosim_top.bd]

read_verilog -library xil_defaultlib /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/sources_1/bd/hwcosim_top/hdl/hwcosim_top_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/constrs_1/imports/sysgen/sum_1_clock.xdc
set_property used_in_implementation false [get_files /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/constrs_1/imports/sysgen/sum_1_clock.xdc]

read_xdc /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/constrs_1/imports/common/jtag_hwcosim_top.xdc
set_property used_in_implementation false [get_files /home/zaid/MTP/myrepo/sysgen/netlist/hwcosim/sum_1.srcs/constrs_1/imports/common/jtag_hwcosim_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top hwcosim_top_wrapper -part xc7vx485tffg1761-2


write_checkpoint -force -noxdef hwcosim_top_wrapper.dcp

catch { report_utilization -file hwcosim_top_wrapper_utilization_synth.rpt -pb hwcosim_top_wrapper_utilization_synth.pb }
