# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /Scratch/vish/Zaid/gps/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.srcs/sources_1/ip/blk_mem_I_1/blk_mem_I.xci
# IP: The module: 'blk_mem_I' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /Scratch/vish/Zaid/gps/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.srcs/sources_1/ip/blk_mem_I_1/blk_mem_I_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_I'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /Scratch/vish/Zaid/gps/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.srcs/sources_1/ip/blk_mem_I_1/blk_mem_I.xci
# IP: The module: 'blk_mem_I' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /Scratch/vish/Zaid/gps/GPS_Ver/Acq_Track_VCU108/Acq_Track_VCU108.srcs/sources_1/ip/blk_mem_I_1/blk_mem_I_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_I'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
